// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0-YgPJ69TU-dL6EB2BBEKlakpGlaaxA',
    appId: '1:504414325498:web:9619d7dd013c8212aed743',
    messagingSenderId: '504414325498',
    projectId: 'barber-apppointment',
    authDomain: 'barber-apppointment.firebaseapp.com',
    storageBucket: 'barber-apppointment.appspot.com',
    measurementId: 'G-V70HLX1D8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJmQ2NtbcL8RNpMeKycg3vmpbuJWZlNl0',
    appId: '1:504414325498:android:dc93011ec6234dceaed743',
    messagingSenderId: '504414325498',
    projectId: 'barber-apppointment',
    storageBucket: 'barber-apppointment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOIXr9XxkdApNLD-qWWOvny6nnh6TzTLc',
    appId: '1:504414325498:ios:8ed0a912494dbdb6aed743',
    messagingSenderId: '504414325498',
    projectId: 'barber-apppointment',
    storageBucket: 'barber-apppointment.appspot.com',
    iosBundleId: 'com.metacortx.barbershopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOIXr9XxkdApNLD-qWWOvny6nnh6TzTLc',
    appId: '1:504414325498:ios:8ed0a912494dbdb6aed743',
    messagingSenderId: '504414325498',
    projectId: 'barber-apppointment',
    storageBucket: 'barber-apppointment.appspot.com',
    iosBundleId: 'com.metacortx.barbershopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL0-YgPJ69TU-dL6EB2BBEKlakpGlaaxA',
    appId: '1:504414325498:web:f1871b493d71ab16aed743',
    messagingSenderId: '504414325498',
    projectId: 'barber-apppointment',
    authDomain: 'barber-apppointment.firebaseapp.com',
    storageBucket: 'barber-apppointment.appspot.com',
    measurementId: 'G-HQB3LM14YY',
  );

}